[build]
  bin = "./tmp/main"
  cmd = '''go build -buildvcs=false -o ./tmp/main .'''

# [proxy]
#   # Enable live-reloading on the browser.
#   enabled = true
#   proxy_port = 3001
#   app_port = 3000
