services:
  app:
    build: .
    ports:
      - "8080:8080" # This dynamically assigns a host port to container port 8080
      - "8081:8081" # This is the live-reloading proxy port (very swag)
    restart: always
    volumes:
      - .:/app
