FROM golang:1.23 AS builder

WORKDIR /app

# Get Go tools
RUN go install github.com/a-h/templ/cmd/templ@latest

# Copy go.mod/go.sum first for caching
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN templ generate
RUN go build -o app

FROM debian:bookworm-slim
WORKDIR /app

COPY --from=builder /app/app ./app
COPY ./static ./static

EXPOSE 3000

CMD ["./app"]
