FROM golang:1.24

RUN apt-get update && apt-get install -y git curl watchman btop

# Get Go tools
RUN go install github.com/air-verse/air@latest
RUN go install github.com/a-h/templ/cmd/templ@latest

WORKDIR /app

RUN git config --global --add safe.directory /app

CMD ["air"]
